export const quotes: string[] = [
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "When you feel like giving up, remember why you held on for so long in the first place.",
  "You are never too far gone to be loved and cherished.",
  "The struggle you're in today is developing the strength you need for tomorrow. — Robert Tew",
  "Do not fear failure but rather fear not trying. — Roy T. Bennett",
  "You are loved, not because you are perfect, but because you are enough.",
  "Every setback is a setup for a comeback. — Joel Osteen",
  "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.",
  "You are stronger than you think, braver than you believe, and loved more than you know.",
  "It's okay to not be okay. What matters is that you keep going.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
  "You are worthy of love, no matter where you are on your journey.",
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway. — Earl Nightingale",
  "Sometimes, the bravest thing you can do is just keep going.",
];
